<?php echo $this->partial('index/header.phtml');?>
<?php echo $this->partial('index/sidebar.phtml');?>
<script>
$(document).ready(function() {
jQuery(".delete").live('click' , function(){
var my_label = $(this).parent().parent();
jQuery(my_label).remove();
});
jQuery(".filter_list").click(function(){
				var id_val = this.id;
				$('#filters_box').append("<p class='filter form-search "+id_val+"'><span class='label label-info form-label'><a class='delete'  href='javascript://'><i class='icon-trash icon-white'></i></a>"+id_val+"</span>&nbsp;&nbsp;&nbsp;<input class='additional-fieldset input-small' type='text' value='' name='"+id_val+"' style='display:inline-block;'></p>");
				});
});
</script>
<?php 
$table_name = Zend_Controller_Front::getInstance()->getRequest()->getParam('table');
?>
<div class="span9">
<h1>Add New <?php echo $table_name; ?></h1>
<hr>
<?php if(isset($_REQUEST['add']) && $_REQUEST['add']=="succ") { ?>
<div class="alert alert-success">
 Your Data has been added successfully 
    </div>
<?php } ?>
<?php if(isset($_REQUEST['edit']) && $_REQUEST['edit']=="succ") { ?>
<div class="alert alert-success">
 Your Data has been saved successfully 
    </div>
<?php } ?>
<ul class="breadcrumb">
<li><a href="/">Dashboard</a></li>
<span class="divider">/</span>
<li><a href="<?php echo $this->url(array( 'controller' => 'index', 'action' => 'tabdetails','table' => $table_name)); ?>"><?php echo $table_name; ?></a></li>
<span class="divider">/</span>
<li><?php echo "new"; ?></li>
</ul>
  <div class="tabbable"> 
    <ul class="nav nav-tabs">
    <li class="icon index_collection_link " rel="" title="">
				<a href="<?php echo $this->url(array( 'controller' => 'index', 'action' => 'tabdetails','table' => $table_name)); ?>" ><i class="icon-th-list"></i><span>List</span></a></li>
    <li class="icon index_collection_link active"><a href="<?php echo $this->url(array( 'controller' => 'index', 'action' => 'addnew','table' => $table_name)); ?>"><i class="icon-plus"></i><span>Add New</span></a></li>
				<li><a href="<?php echo $this->url(array( 'controller' => 'index', 'action' => 'export','table' => $table_name)); ?>"><i class="icon-share"></i><span>Export</span></a></li>
				<li><a href="<?php echo $this->url(array( 'controller' => 'index', 'action' => 'history','table' => $table_name)); ?>">	<i class="icon-book"></i><span>History</span></a></li>
    </ul>
									<form  class="form-horizontal denser" method="post" enctype="multipart/form-data" action="<?php echo $this->url(array( 'controller' => 'index', 'action' => 'addnew','table' => $table_name)); ?>" accept-charset="UTF-8">
							<div style="margin:0;padding:0;display:inline">
							</div>
							<fieldset>
							<legend style="display:none">
							<i class="icon-chevron-down"></i>
							</legend>
						<?php    for($i=0;$i<count($this->desc);$i++) {  
						if($this->desc[$i]['Extra'] !="auto_increment" && $this->desc[$i]['Type'] != "int(11)") {
						?>
						<div style=" margin-bottom:10px;">
							<label class="control-label" for="<?php echo $this->desc[$i]['Field']; ?>"><?php echo $this->desc[$i]['Field']; ?></label>
									<div class="controls">
																	<input type="text" name="<?php echo $this->desc[$i]['Field']; ?>" id="<?php echo $this->desc[$i]['Field']; ?>" required="required">
									</div>
						</div>
																							<?php 
																						 	}
																							} ?>
										</fieldset>
								<input type="hidden" name="table_name" value="<?php echo $table_name; ?>" id="table_name">
								<div class="form-actions">
								<button class="btn btn-primary" type="submit" name="_save" data-disable-with="Save">
								<i class="icon-white icon-ok"></i>
								Save
								</button>
								<span class="extra_buttons">
								<button class="btn btn-info" type="submit" name="_add_another" data-disable-with="Save and add another"> Save and add another </button>
								<button class="btn btn-info" type="submit" name="_add_edit" data-disable-with="Save and edit"> Save and edit </button>
								<a class="btn cancel"  name="_continue" data-disable-with="Cancel" href="/index/tabdetails/table/<?php echo $table_name; ?>?add=cancel">
								<i class="icon-remove"></i>
								Cancel
								</a>
								</span>
								</div>
</form>
							</div>
   
</div>
</body>
<?php echo $this->partial('index/footer.phtml');?>
</html>