<?php echo $this->partial('index/header.phtml');?>
<?php echo $this->partial('index/sidebar.phtml');?>
<?php 
$table_name = Zend_Controller_Front::getInstance()->getRequest()->getParam('table');
$id_value = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
$id_name = Zend_Controller_Front::getInstance()->getRequest()->getParam('id_name');
?>
<div class="span9">
<h1>Details of <?php echo $table_name." #".$id_value; ?></h1>
<hr>
<?php if(isset($_REQUEST['edit']) && $_REQUEST['edit']=="succ") { ?>
<div class="alert alert-success">
 Your Data has been Saved successfully 
    </div>
<?php } ?>
<?php if(isset($_REQUEST['edit']) && $_REQUEST['edit']=="cancel") { ?>
<div class="alert alert-info">
You have cancalled the functionality
    </div>
<?php } ?>
<ul class="breadcrumb">
<li><a href="/">Dashboard</a></li>
<span class="divider">/</span>
<li><a href="<?php echo $this->url(array( 'controller' => 'index', 'action' => 'tabdetails','table' => $table_name)); ?>"><?php echo $table_name; ?></a></li>
<span class="divider">/</span>
<li><?php echo $table_name ." #".$id_value; ?></li>
</ul>

  <div class="tabbable"> 
							<ul class="nav nav-tabs">
														<li class="icon index_collection_link active" rel="" title="">
														<a href="<?php echo $this->url(array( 'controller' => 'index', 'action' => 'show','table' => $table_name)); ?>" ><i class="icon-info-sign"></i><span>Show</span></a></li>
														<li ><a href="<?php echo $this->url(array( 'controller' => 'index', 'action' => 'edit','table' => $table_name)); ?>">		<i class="icon-pencil"></i><span>Edit</span></a></li>
														<li class="icon index_collection_link"><a href="<?php echo $this->url(array( 'controller' => 'index', 'action' => 'delete','table' => $table_name)); ?>">	<i class="icon-remove"></i><span>Delete</span></a></li>
														<li><a href="<?php echo $this->url(array( 'controller' => 'index', 'action' => 'history','table' => $table_name)); ?>" >	<i class="icon-book"></i><span>History</span></a></li>
							</ul>
							
							<strong>Basic Info</strong>
							<dl>
						<?php	foreach($this->result as $key=>$val) {
						if($id_value != $val && $id_name!=$key) {
						 ?>
						 				<dt class="label"><?php echo $key; ?></dt>
											<dd><pre class="prettyprint"><?php echo $val; ?></pre></dd>
											
							<?php	} } ?>
							</dl>
   
				</div>
				<?php echo $this->partial('index/footer.phtml');?>
</div>
</body>


</html>